/**
 * Created by rahilvora on 30/04/16.
 */

var data =[
    {
        "productid": 1,
        "farmerid": "11-848-9999",
        "farmername": "Garza Gilbert",
        "productname": "potatoes",
        "productprice": 9.32,
        "description": "These are fresh potatoes",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 2,
        "farmerid": "11-589-9999",
        "farmername": "Leila Goodman",
        "productname": "tomatoes",
        "productprice": 7.99,
        "description": "These are fresh tomatoes",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 3,
        "farmerid": "11-786-9999",
        "farmername": "Boone Jordan",
        "productname": "tomatoes",
        "productprice": 2.31,
        "description": "These are fresh tomatoes",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 4,
        "farmerid": "11-13-9999",
        "farmername": "Lelia Mcgee",
        "productname": "banana",
        "productprice": 0.47,
        "description": "These are fresh banana",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 5,
        "farmerid": "11-415-9999",
        "farmername": "Walton Dominguez",
        "productname": "carrots",
        "productprice": 3.77,
        "description": "These are fresh carrots",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 6,
        "farmerid": "11-432-9999",
        "farmername": "Terry Parsons",
        "productname": "banana",
        "productprice": 6.75,
        "description": "These are fresh banana",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 7,
        "farmerid": "11-93-9999",
        "farmername": "Juanita Ramos",
        "productname": "carrots",
        "productprice": 2.84,
        "description": "These are fresh carrots",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 8,
        "farmerid": "11-633-9999",
        "farmername": "Mays Cooley",
        "productname": "cabbage",
        "productprice": 4.76,
        "description": "These are fresh cabbage",
        "category": "Sprouts",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 9,
        "farmerid": "11-463-9999",
        "farmername": "Kari Harris",
        "productname": "banana",
        "productprice": 9.5,
        "description": "These are fresh banana",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 10,
        "farmerid": "11-28-9999",
        "farmername": "Elvira Abbott",
        "productname": "cabbage",
        "productprice": 1.33,
        "description": "These are fresh cabbage",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 11,
        "farmerid": "11-58-9999",
        "farmername": "Moody Hendricks",
        "productname": "cabbage",
        "productprice": 7.06,
        "description": "These are fresh cabbage",
        "category": "Vegetables",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 12,
        "farmerid": "11-246-9999",
        "farmername": "Branch Best",
        "productname": "tomatoes",
        "productprice": 7.31,
        "description": "These are fresh tomatoes",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 13,
        "farmerid": "11-454-9999",
        "farmername": "Millicent Horne",
        "productname": "grapes",
        "productprice": 3.74,
        "description": "These are fresh grapes",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 14,
        "farmerid": "11-646-9999",
        "farmername": "Anna Golden",
        "productname": "carrots",
        "productprice": 2.31,
        "description": "These are fresh carrots",
        "category": "fruits",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 15,
        "farmerid": "11-104-9999",
        "farmername": "Campos Curry",
        "productname": "banana",
        "productprice": 5.97,
        "description": "These are fresh banana",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 16,
        "farmerid": "11-765-9999",
        "farmername": "Curtis Serrano",
        "productname": "banana",
        "productprice": 0.76,
        "description": "These are fresh banana",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 17,
        "farmerid": "11-427-9999",
        "farmername": "Holland Lamb",
        "productname": "potatoes",
        "productprice": 6.91,
        "description": "These are fresh potatoes",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 18,
        "farmerid": "11-119-9999",
        "farmername": "Cotton Faulkner",
        "productname": "grapes",
        "productprice": 6.18,
        "description": "These are fresh grapes",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 19,
        "farmerid": "11-948-9999",
        "farmername": "Donna Delgado",
        "productname": "peas",
        "productprice": 4.21,
        "description": "These are fresh peas",
        "category": "Pulses",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 20,
        "farmerid": "11-244-9999",
        "farmername": "Guerrero Downs",
        "productname": "apple",
        "productprice": 5.95,
        "description": "These are fresh apple",
        "category": "Sprouts",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 21,
        "farmerid": "11-122-9999",
        "farmername": "Teresa Patrick",
        "productname": "grapes",
        "productprice": 2.96,
        "description": "These are fresh grapes",
        "category": "Vegetables",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 22,
        "farmerid": "11-906-9999",
        "farmername": "Cleo Lindsey",
        "productname": "onins",
        "productprice": 8.5,
        "description": "These are fresh onins",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 23,
        "farmerid": "11-354-9999",
        "farmername": "Irwin Leonard",
        "productname": "onins",
        "productprice": 8.92,
        "description": "These are fresh onins",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 24,
        "farmerid": "11-71-9999",
        "farmername": "Mabel Floyd",
        "productname": "tomatoes",
        "productprice": 0.92,
        "description": "These are fresh tomatoes",
        "category": "Pulses",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 25,
        "farmerid": "11-892-9999",
        "farmername": "Bruce Robbins",
        "productname": "cabbage",
        "productprice": 8.11,
        "description": "These are fresh cabbage",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 26,
        "farmerid": "11-363-9999",
        "farmername": "Young Hill",
        "productname": "peas",
        "productprice": 7.76,
        "description": "These are fresh peas",
        "category": "Sprouts",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 27,
        "farmerid": "11-422-9999",
        "farmername": "Ryan Wells",
        "productname": "banana",
        "productprice": 5.45,
        "description": "These are fresh banana",
        "category": "fruits",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 28,
        "farmerid": "11-986-9999",
        "farmername": "Nell Baker",
        "productname": "banana",
        "productprice": 8.26,
        "description": "These are fresh banana",
        "category": "Vegetables",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 29,
        "farmerid": "11-802-9999",
        "farmername": "Viola Evans",
        "productname": "cabbage",
        "productprice": 1.29,
        "description": "These are fresh cabbage",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 30,
        "farmerid": "11-653-9999",
        "farmername": "Stacey Weeks",
        "productname": "potatoes",
        "productprice": 6.13,
        "description": "These are fresh potatoes",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 31,
        "farmerid": "11-37-9999",
        "farmername": "Logan Griffith",
        "productname": "tomatoes",
        "productprice": 8.29,
        "description": "These are fresh tomatoes",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 32,
        "farmerid": "11-536-9999",
        "farmername": "Camacho Buckner",
        "productname": "lentils",
        "productprice": 8.98,
        "description": "These are fresh lentils",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 33,
        "farmerid": "11-194-9999",
        "farmername": "Shirley Simpson",
        "productname": "apple",
        "productprice": 1.9,
        "description": "These are fresh apple",
        "category": "Sprouts",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 34,
        "farmerid": "11-617-9999",
        "farmername": "Stephenson Lynch",
        "productname": "grapes",
        "productprice": 9.73,
        "description": "These are fresh grapes",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 35,
        "farmerid": "11-151-9999",
        "farmername": "Claudia Stanton",
        "productname": "tomatoes",
        "productprice": 0.72,
        "description": "These are fresh tomatoes",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 36,
        "farmerid": "11-706-9999",
        "farmername": "Jeannine Mcclure",
        "productname": "potatoes",
        "productprice": 8.35,
        "description": "These are fresh potatoes",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 37,
        "farmerid": "11-37-9999",
        "farmername": "Hunt Montgomery",
        "productname": "tomatoes",
        "productprice": 2.34,
        "description": "These are fresh tomatoes",
        "category": "fruits",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 38,
        "farmerid": "11-510-9999",
        "farmername": "Dale Hurley",
        "productname": "grapes",
        "productprice": 5.86,
        "description": "These are fresh grapes",
        "category": "Vegetables",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 39,
        "farmerid": "11-547-9999",
        "farmername": "Edna Middleton",
        "productname": "carrots",
        "productprice": 2.59,
        "description": "These are fresh carrots",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 40,
        "farmerid": "11-742-9999",
        "farmername": "Bradshaw Mclean",
        "productname": "cabbage",
        "productprice": 1.88,
        "description": "These are fresh cabbage",
        "category": "Pulses",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 41,
        "farmerid": "11-888-9999",
        "farmername": "Mueller Strong",
        "productname": "apple",
        "productprice": 7.71,
        "description": "These are fresh apple",
        "category": "Pulses",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 42,
        "farmerid": "11-159-9999",
        "farmername": "Misty Snyder",
        "productname": "cabbage",
        "productprice": 9.44,
        "description": "These are fresh cabbage",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 43,
        "farmerid": "11-727-9999",
        "farmername": "Emerson Pitts",
        "productname": "grapes",
        "productprice": 2.85,
        "description": "These are fresh grapes",
        "category": "Pulses",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 44,
        "farmerid": "11-139-9999",
        "farmername": "Stanton Hammond",
        "productname": "grapes",
        "productprice": 1.07,
        "description": "These are fresh grapes",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 45,
        "farmerid": "11-350-9999",
        "farmername": "Lacy Drake",
        "productname": "lentils",
        "productprice": 8.19,
        "description": "These are fresh lentils",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 46,
        "farmerid": "11-803-9999",
        "farmername": "Mcmahon Estrada",
        "productname": "apple",
        "productprice": 6.67,
        "description": "These are fresh apple",
        "category": "fruits",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 47,
        "farmerid": "11-507-9999",
        "farmername": "Camille Craig",
        "productname": "peas",
        "productprice": 9.88,
        "description": "These are fresh peas",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 48,
        "farmerid": "11-419-9999",
        "farmername": "Young Holt",
        "productname": "apple",
        "productprice": 0.04,
        "description": "These are fresh apple",
        "category": "fruits",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 49,
        "farmerid": "11-841-9999",
        "farmername": "Martha Slater",
        "productname": "apple",
        "productprice": 1.23,
        "description": "These are fresh apple",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 50,
        "farmerid": "11-892-9999",
        "farmername": "Mcleod Cooper",
        "productname": "cabbage",
        "productprice": 8.3,
        "description": "These are fresh cabbage",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 51,
        "farmerid": "11-666-9999",
        "farmername": "Lara Donaldson",
        "productname": "onins",
        "productprice": 3.2,
        "description": "These are fresh onins",
        "category": "Sprouts",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 52,
        "farmerid": "11-80-9999",
        "farmername": "Eddie Maddox",
        "productname": "carrots",
        "productprice": 2.35,
        "description": "These are fresh carrots",
        "category": "Sprouts",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 53,
        "farmerid": "11-870-9999",
        "farmername": "Zamora Mccray",
        "productname": "garlic",
        "productprice": 2.89,
        "description": "These are fresh garlic",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 54,
        "farmerid": "11-407-9999",
        "farmername": "Sue Conley",
        "productname": "peas",
        "productprice": 6.72,
        "description": "These are fresh peas",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 55,
        "farmerid": "11-597-9999",
        "farmername": "Yvonne James",
        "productname": "banana",
        "productprice": 7.59,
        "description": "These are fresh banana",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 56,
        "farmerid": "11-879-9999",
        "farmername": "Karyn Hart",
        "productname": "onins",
        "productprice": 8.08,
        "description": "These are fresh onins",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 57,
        "farmerid": "11-154-9999",
        "farmername": "Lorene Rosales",
        "productname": "tomatoes",
        "productprice": 5.83,
        "description": "These are fresh tomatoes",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 58,
        "farmerid": "11-402-9999",
        "farmername": "Lori Justice",
        "productname": "lentils",
        "productprice": 0.41,
        "description": "These are fresh lentils",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 59,
        "farmerid": "11-365-9999",
        "farmername": "Houston Sheppard",
        "productname": "potatoes",
        "productprice": 8.92,
        "description": "These are fresh potatoes",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 60,
        "farmerid": "11-55-9999",
        "farmername": "Kimberley Holder",
        "productname": "banana",
        "productprice": 2.92,
        "description": "These are fresh banana",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 61,
        "farmerid": "11-905-9999",
        "farmername": "Knight Preston",
        "productname": "potatoes",
        "productprice": 9,
        "description": "These are fresh potatoes",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 62,
        "farmerid": "11-128-9999",
        "farmername": "Althea Church",
        "productname": "tomatoes",
        "productprice": 6.88,
        "description": "These are fresh tomatoes",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 63,
        "farmerid": "11-868-9999",
        "farmername": "Tammy Fulton",
        "productname": "banana",
        "productprice": 6.39,
        "description": "These are fresh banana",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 64,
        "farmerid": "11-546-9999",
        "farmername": "Langley Howe",
        "productname": "potatoes",
        "productprice": 8.83,
        "description": "These are fresh potatoes",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 65,
        "farmerid": "11-214-9999",
        "farmername": "Wilder Ochoa",
        "productname": "lentils",
        "productprice": 7.39,
        "description": "These are fresh lentils",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 66,
        "farmerid": "11-896-9999",
        "farmername": "Wooten Mueller",
        "productname": "peas",
        "productprice": 1.44,
        "description": "These are fresh peas",
        "category": "fruits",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 67,
        "farmerid": "11-131-9999",
        "farmername": "Allen Griffin",
        "productname": "garlic",
        "productprice": 0.51,
        "description": "These are fresh garlic",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 68,
        "farmerid": "11-654-9999",
        "farmername": "Rosie Newton",
        "productname": "apple",
        "productprice": 1.71,
        "description": "These are fresh apple",
        "category": "Pulses",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 69,
        "farmerid": "11-299-9999",
        "farmername": "Lauren Rose",
        "productname": "cabbage",
        "productprice": 9.29,
        "description": "These are fresh cabbage",
        "category": "fruits",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 70,
        "farmerid": "11-420-9999",
        "farmername": "Jensen Conrad",
        "productname": "potatoes",
        "productprice": 2.62,
        "description": "These are fresh potatoes",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 71,
        "farmerid": "11-367-9999",
        "farmername": "Luella David",
        "productname": "apple",
        "productprice": 1.29,
        "description": "These are fresh apple",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 72,
        "farmerid": "11-102-9999",
        "farmername": "Blake Hoffman",
        "productname": "banana",
        "productprice": 0.47,
        "description": "These are fresh banana",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 73,
        "farmerid": "11-342-9999",
        "farmername": "Tina Frost",
        "productname": "tomatoes",
        "productprice": 7.37,
        "description": "These are fresh tomatoes",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 74,
        "farmerid": "11-76-9999",
        "farmername": "Holcomb Mercer",
        "productname": "carrots",
        "productprice": 3.62,
        "description": "These are fresh carrots",
        "category": "Vegetables",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 75,
        "farmerid": "11-110-9999",
        "farmername": "Patrica Garrison",
        "productname": "banana",
        "productprice": 7.25,
        "description": "These are fresh banana",
        "category": "fruits",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 76,
        "farmerid": "11-697-9999",
        "farmername": "Howell Clemons",
        "productname": "grapes",
        "productprice": 0.63,
        "description": "These are fresh grapes",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 77,
        "farmerid": "11-488-9999",
        "farmername": "Richardson Herring",
        "productname": "garlic",
        "productprice": 4.02,
        "description": "These are fresh garlic",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 78,
        "farmerid": "11-155-9999",
        "farmername": "Juarez Rowland",
        "productname": "garlic",
        "productprice": 8.82,
        "description": "These are fresh garlic",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 79,
        "farmerid": "11-849-9999",
        "farmername": "Florence Jenkins",
        "productname": "cabbage",
        "productprice": 1.99,
        "description": "These are fresh cabbage",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 80,
        "farmerid": "11-801-9999",
        "farmername": "Dejesus Salazar",
        "productname": "grapes",
        "productprice": 5.52,
        "description": "These are fresh grapes",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 81,
        "farmerid": "11-532-9999",
        "farmername": "Trevino Love",
        "productname": "potatoes",
        "productprice": 2.03,
        "description": "These are fresh potatoes",
        "category": "Sprouts",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 1
    },
    {
        "productid": 82,
        "farmerid": "11-513-9999",
        "farmername": "Higgins Jennings",
        "productname": "apple",
        "productprice": 2.94,
        "description": "These are fresh apple",
        "category": "fruits",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 83,
        "farmerid": "11-756-9999",
        "farmername": "Hendrix Rhodes",
        "productname": "lentils",
        "productprice": 5.5,
        "description": "These are fresh lentils",
        "category": "Vegetables",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 84,
        "farmerid": "11-924-9999",
        "farmername": "Carrie Miles",
        "productname": "tomatoes",
        "productprice": 5.45,
        "description": "These are fresh tomatoes",
        "category": "Vegetables",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 85,
        "farmerid": "11-936-9999",
        "farmername": "Wynn Whitaker",
        "productname": "carrots",
        "productprice": 0.1,
        "description": "These are fresh carrots",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 86,
        "farmerid": "11-839-9999",
        "farmername": "Colette Black",
        "productname": "banana",
        "productprice": 9.96,
        "description": "These are fresh banana",
        "category": "Pulses",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 87,
        "farmerid": "11-46-9999",
        "farmername": "Bobbi Harrell",
        "productname": "potatoes",
        "productprice": 0.94,
        "description": "These are fresh potatoes",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 88,
        "farmerid": "11-580-9999",
        "farmername": "Tameka Fry",
        "productname": "banana",
        "productprice": 0.9,
        "description": "These are fresh banana",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 89,
        "farmerid": "11-579-9999",
        "farmername": "Francesca Potts",
        "productname": "onins",
        "productprice": 5.66,
        "description": "These are fresh onins",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 90,
        "farmerid": "11-522-9999",
        "farmername": "Candice Santiago",
        "productname": "lentils",
        "productprice": 3.09,
        "description": "These are fresh lentils",
        "category": "Vegetables",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 5
    },
    {
        "productid": 91,
        "farmerid": "11-96-9999",
        "farmername": "Hilary Ford",
        "productname": "potatoes",
        "productprice": 9.63,
        "description": "These are fresh potatoes",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 0
    },
    {
        "productid": 92,
        "farmerid": "11-349-9999",
        "farmername": "Loraine Lang",
        "productname": "garlic",
        "productprice": 4.57,
        "description": "These are fresh garlic",
        "category": "fruits",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 93,
        "farmerid": "11-489-9999",
        "farmername": "Lynn Myers",
        "productname": "garlic",
        "productprice": 5.69,
        "description": "These are fresh garlic",
        "category": "Pulses",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 94,
        "farmerid": "11-597-9999",
        "farmername": "Jeanie Calderon",
        "productname": "potatoes",
        "productprice": 8.23,
        "description": "These are fresh potatoes",
        "category": "Vegetables",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 95,
        "farmerid": "11-100-9999",
        "farmername": "Poole Pollard",
        "productname": "garlic",
        "productprice": 7.74,
        "description": "These are fresh garlic",
        "category": "Pulses",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 96,
        "farmerid": "11-399-9999",
        "farmername": "Hattie Mullen",
        "productname": "lentils",
        "productprice": 2.74,
        "description": "These are fresh lentils",
        "category": "Sprouts",
        "active": true,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    },
    {
        "productid": 97,
        "farmerid": "11-646-9999",
        "farmername": "Isabel Stephens",
        "productname": "carrots",
        "productprice": 4.19,
        "description": "These are fresh carrots",
        "category": "Sprouts",
        "active": false,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 3
    },
    {
        "productid": 98,
        "farmerid": "11-204-9999",
        "farmername": "Beasley Lyons",
        "productname": "banana",
        "productprice": 3.65,
        "description": "These are fresh banana",
        "category": "Sprouts",
        "active": true,
        "approved": false,
        "productimage": {},
        "productreviews": [],
        "productrating": 4
    },
    {
        "productid": 99,
        "farmerid": "11-155-9999",
        "farmername": "Ola Knowles",
        "productname": "apple",
        "productprice": 5.36,
        "description": "These are fresh apple",
        "category": "Sprouts",
        "active": false,
        "approved": true,
        "productimage": {},
        "productreviews": [],
        "productrating": 2
    }
]

module.exports = data;